<?php
/**
 * Database Setup Script
 * 
 * This script helps you set up the database for the Purchase Management System.
 * It will:
 * 1. Test the database connection with the provided credentials
 * 2. Create the database if it doesn't exist
 * 3. Import the schema from db.sql
 * 4. Create a test admin user
 */

// Start session for potential messages
session_start();

// Function to display messages
function display_message($type, $message) {
    echo "<div class='alert alert-$type' role='alert'>$message</div>";
}

// Process form submission
$setup_complete = false;
$error = '';
$success = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Get form data
    $host = $_POST['host'] ?? 'localhost';
    $user = $_POST['username'] ?? '';
    $pwd = $_POST['password'] ?? '';
    $db = $_POST['database'] ?? 'purchase_requisition';
    
    // Validate input
    if (empty($user)) {
        $error = "Username is required";
    } else {
        try {
            // Try to connect to MySQL
            $con = new mysqli($host, $user, $pwd);
            
            if ($con->connect_error) {
                $error = "Connection failed: " . $con->connect_error;
            } else {
                // Check if database exists
                $result = $con->query("SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '$db'");
                $db_exists = ($result && $result->num_rows > 0);
                
                if (!$db_exists) {
                    // Create database
                    if (!$con->query("CREATE DATABASE IF NOT EXISTS `$db`")) {
                        $error = "Error creating database: " . $con->error;
                    } else {
                        $success .= "Database '$db' created successfully.<br>";
                    }
                } else {
                    $success .= "Database '$db' already exists.<br>";
                }
                
                if (empty($error)) {
                    // Select database
                    $con->select_db($db);
                    
                    // Import schema from db.sql
                    $sql_file = file_get_contents(__DIR__ . '/db.sql');
                    if ($sql_file) {
                        // Split SQL file into individual statements
                        $statements = explode(';', $sql_file);
                        
                        foreach ($statements as $statement) {
                            $statement = trim($statement);
                            if (!empty($statement)) {
                                if (!$con->query($statement . ';')) {
                                    $error = "Error importing schema: " . $con->error;
                                    break;
                                }
                            }
                        }
                        
                        if (empty($error)) {
                            $success .= "Schema imported successfully.<br>";
                            
                            // Create a test admin user
                            $admin_name = "Admin User";
                            $admin_email = "admin@example.com";
                            $admin_password = password_hash("admin123", PASSWORD_DEFAULT);
                            
                            // Check if admin user already exists
                            $check = $con->query("SELECT * FROM users WHERE email = 'admin@example.com'");
                            if ($check && $check->num_rows == 0) {
                                $stmt = $con->prepare("INSERT INTO users (full_name, email, role, password) VALUES (?, ?, 'admin', ?)");
                                $stmt->bind_param("sss", $admin_name, $admin_email, $admin_password);
                                
                                if ($stmt->execute()) {
                                    $success .= "Admin user created successfully.<br>Email: admin@example.com<br>Password: admin123<br>";
                                } else {
                                    $error = "Error creating admin user: " . $stmt->error;
                                }
                            } else {
                                $success .= "Admin user already exists.<br>";
                            }
                            
                            // Create local_config.php
                            $config_content = "<?php\n";
                            $config_content .= "// Database configuration - Auto-generated by setup script\n";
                            $config_content .= "\$host = '$host';\n";
                            $config_content .= "\$user = '$user';\n";
                            $config_content .= "\$pwd = '$pwd';\n";
                            $config_content .= "\$db = '$db';\n";
                            $config_content .= "?>";
                            
                            if (file_put_contents(__DIR__ . '/includes/local_config.php', $config_content)) {
                                $success .= "Configuration file created successfully.<br>";
                                $setup_complete = true;
                            } else {
                                $error = "Error creating configuration file. Please check file permissions.";
                            }
                        }
                    } else {
                        $error = "Could not read schema file";
                    }
                }
            }
        } catch (Exception $e) {
            $error = "Error: " . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Database Setup - Purchase Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f8f9fa;
            padding-top: 2rem;
        }
        .setup-container {
            max-width: 800px;
            margin: 0 auto;
            background-color: white;
            border-radius: 5px;
            box-shadow: 0 0.15rem 1.75rem 0 rgba(58, 59, 69, 0.15);
            padding: 2rem;
        }
        .header {
            text-align: center;
            margin-bottom: 2rem;
        }
        .form-group {
            margin-bottom: 1rem;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="setup-container">
            <div class="header">
                <h1>Purchase Management System</h1>
                <h3>Database Setup</h3>
            </div>
            
            <?php if ($setup_complete): ?>
                <div class="alert alert-success">
                    <h4>Setup Complete!</h4>
                    <p>The database has been set up successfully.</p>
                    <p><?php echo $success; ?></p>
                    <a href="login.php" class="btn btn-primary">Go to Login Page</a>
                </div>
            <?php else: ?>
                <?php if ($error): ?>
                    <div class="alert alert-danger"><?php echo $error; ?></div>
                <?php endif; ?>
                
                <?php if ($success): ?>
                    <div class="alert alert-success"><?php echo $success; ?></div>
                <?php endif; ?>
                
                <form method="post" action="">
                    <div class="form-group">
                        <label for="host">Database Host:</label>
                        <input type="text" class="form-control" id="host" name="host" value="localhost" required>
                        <small class="form-text text-muted">Usually 'localhost' or '127.0.0.1'</small>
                    </div>
                    
                    <div class="form-group">
                        <label for="username">MySQL Username:</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="password">MySQL Password:</label>
                        <input type="password" class="form-control" id="password" name="password">
                        <small class="form-text text-muted">Leave empty if no password is required</small>
                    </div>
                    
                    <div class="form-group">
                        <label for="database">Database Name:</label>
                        <input type="text" class="form-control" id="database" name="database" value="purchase_requisition" required>
                    </div>
                    
                    <div class="alert alert-info">
                        <h5>What this setup will do:</h5>
                        <ul>
                            <li>Test the database connection with the provided credentials</li>
                            <li>Create the database if it doesn't exist</li>
                            <li>Import the schema from db.sql</li>
                            <li>Create a test admin user</li>
                            <li>Save your database configuration</li>
                        </ul>
                    </div>
                    
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">Set Up Database</button>
                    </div>
                </form>
            <?php endif; ?>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
